### ISSUE TITLE
Segfault on Linux x86_64; v0.5

### ISSUE THREAD

**Issue by chadjoan** [ferru97/Rai-Net-Access-Battlers---Official#2]
I just downloaded version 0.5 from the website and unzipped it. I tried to run the `rainet-access-battlers-v0.5.x86_64` executable and it segfaulted.

So I ran it with `gdb` and this is what the session looked like:
```
chad@Hugin ~/downloads/games/Rai-Net-Access-Battlers/v0.5-bin $ ll
total 44323
-rwxr-xr-x 1 chad chad    16064 Apr  3 00:55 LinuxPlayer_s.debug
drwxr-xr-x 5 chad chad       23 Jul 14 18:52 rainet-access-battlers-v0.5_Data
-rwxr-xr-x 1 chad chad    14744 Apr  3 00:55 rainet-access-battlers-v0.5.x86_64
-rwxr-xr-x 1 chad chad 41332216 Apr  3 00:55 UnityPlayer_s.debug
-rwxr-xr-x 1 chad chad 33571544 Apr  3 00:55 UnityPlayer.so
chad@Hugin ~/downloads/games/Rai-Net-Access-Battlers/v0.5-bin $ mono rainet-access-battlers-v0.5.x86_64 
Cannot open assembly 'rainet-access-battlers-v0.5.x86_64': File does not contain a valid CIL image.
chad@Hugin ~/downloads/games/Rai-Net-Access-Battlers/v0.5-bin $ file rainet-access-battlers-v0.5.x86_64 
rainet-access-battlers-v0.5.x86_64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.10.0, BuildID[xxHash]=8a05c17977eacb65, stripped
chad@Hugin ~/downloads/games/Rai-Net-Access-Battlers/v0.5-bin $ gdb rainet-access-battlers-v0.5.x86_64 
GNU gdb (Gentoo 9.1 vanilla) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from rainet-access-battlers-v0.5.x86_64...
Reading symbols from /mnt/sharedhd/srv/encrypted_data/home/chad/downloads/games/Rai-Net-Access-Battlers/v0.5-bin/LinuxPlayer_s.debug...
(No debugging symbols found in /mnt/sharedhd/srv/encrypted_data/home/chad/downloads/games/Rai-Net-Access-Battlers/v0.5-bin/LinuxPlayer_s.debug)
(gdb) run
Starting program: /mnt/sharedhd/srv/encrypted_data/home/chad/downloads/games/Rai-Net-Access-Battlers/v0.5-bin/rainet-access-battlers-v0.5.x86_64 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Found path: /mnt/sharedhd/srv/encrypted_data/home/chad/downloads/games/Rai-Net-Access-Battlers/v0.5-bin/rainet-access-battlers-v0.5.x86_64
[New Thread 0x7ffff5b22640 (LWP 14670)]
[New Thread 0x7fff3f963640 (LWP 16127)]
[New Thread 0x7fff3f015640 (LWP 16128)]
[New Thread 0x7fff3e814640 (LWP 16129)]
[New Thread 0x7fff3e013640 (LWP 16130)]
[New Thread 0x7fff3d812640 (LWP 16131)]
[New Thread 0x7fff3d011640 (LWP 16132)]
[New Thread 0x7fff3c810640 (LWP 16133)]
[New Thread 0x7fff26b3d640 (LWP 16134)]
[New Thread 0x7fff2693c640 (LWP 16135)]
[New Thread 0x7fff2613b640 (LWP 16136)]
[New Thread 0x7fff2593a640 (LWP 16137)]
[New Thread 0x7fff25139640 (LWP 16138)]
[New Thread 0x7fff24938640 (LWP 16139)]
[New Thread 0x7fff1bfff640 (LWP 16140)]
[New Thread 0x7fff1b7fe640 (LWP 16141)]
[New Thread 0x7fff1affd640 (LWP 16142)]
[New Thread 0x7fff1a7fc640 (LWP 16143)]
[New Thread 0x7fff19ffb640 (LWP 16144)]
[New Thread 0x7fff197fa640 (LWP 16145)]
[New Thread 0x7fff18ff9640 (LWP 16146)]
[New Thread 0x7fff13fff640 (LWP 16147)]
[New Thread 0x7fff137fe640 (LWP 16148)]
[New Thread 0x7fff12ffd640 (LWP 16149)]
[New Thread 0x7fff127fc640 (LWP 16150)]
[New Thread 0x7fff11ffb640 (LWP 16151)]
[New Thread 0x7fff117fa640 (LWP 16152)]

Thread 1 "rainet-access-b" received signal SIGSEGV, Segmentation fault.
0x00007ffff6dbc3a8 in AtomicStack::Pop() () from UnityPlayer.so
(gdb) bt
#0  0x00007ffff6dbc3a8 in AtomicStack::Pop() () from UnityPlayer.so
#1  0x00007ffff6abdcf4 in BucketAllocator::Allocate(unsigned long, int) () from UnityPlayer.so
#2  0x00007ffff6abe2fd in DualThreadAllocator<DynamicHeapAllocator>::Allocate(unsigned long, int) () from UnityPlayer.so
#3  0x00007ffff6ab9e40 in MemoryManager::Allocate(unsigned long, unsigned long, MemLabelId, AllocateOptions, char const*, int) () from UnityPlayer.so
#4  0x00007ffff6ab9bc1 in malloc_internal(unsigned long, unsigned long, MemLabelId, AllocateOptions, char const*, int) () from UnityPlayer.so
#5  0x00007ffff7998965 in FMOD::MemPool::alloc(int, char const*, int, unsigned int, bool) () from UnityPlayer.so
#6  0x00007ffff7a3b15b in FMOD::OutputALSA::addALSADriver(char const*) () from UnityPlayer.so
#7  0x00007ffff7a3b3b8 in FMOD::OutputALSA::getALSAConfigDrivers(char const*) () from UnityPlayer.so
#8  0x00007ffff7a3b5bc in FMOD::OutputALSA::enumerate() () from UnityPlayer.so
#9  0x00007ffff7a3b7c4 in FMOD::OutputALSA::init(int, unsigned int, int*, int, FMOD_SOUND_FORMAT*, int, int, void*) () from UnityPlayer.so
#10 0x00007ffff79c01b8 in FMOD::SystemI::init(int, unsigned int, void*) () from UnityPlayer.so
#11 0x00007ffff79b554e in FMOD::System::init(int, unsigned int, void*) () from UnityPlayer.so
#12 0x00007ffff7081427 in AudioManager::InitNormal(bool, FMOD_OUTPUTTYPE) () from UnityPlayer.so
#13 0x00007ffff7080624 in AudioManager::InitFMOD(FMOD_OUTPUTTYPE) () from UnityPlayer.so
#14 0x00007ffff70837aa in AudioManager::AwakeFromLoad(AwakeFromLoadMode) () from UnityPlayer.so
#15 0x00007ffff6ed0da7 in AwakeFromLoadQueue::InvokePersistentManagerAwake(AwakeFromLoadQueue::Item*, unsigned int, AwakeFromLoadMode, bool) () from UnityPlayer.so
#16 0x00007ffff6ed0635 in AwakeFromLoadQueue::PersistentManagerAwakeFromLoad() () from UnityPlayer.so
#17 0x00007ffff6ebc693 in PersistentManager::LoadAndIntegrateAllPreallocatedObjects(PersistentManager::LockFlags) () from UnityPlayer.so
#18 0x00007ffff6ebcc4b in PersistentManager::ReadObject(int, AwakeFromLoadMode) () from UnityPlayer.so
#19 0x00007ffff6acd51e in PlayerLoadGlobalManagers(char const*, char const*, unsigned int) () from UnityPlayer.so
#20 0x00007ffff6d03ba9 in PlayerInitEngineGraphics(bool) () from UnityPlayer.so
#21 0x00007ffff6ee05ad in PlayerMain(int, char**) () from UnityPlayer.so
#22 0x00007ffff5b5ae6b in __libc_start_main (main=0x2010e0 <main>, argc=1, argv=0x7fffffffcd38, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffcd28) at ../csu/libc-start.c:314
#23 0x0000000000201029 in _start ()
(gdb)
```

Interestingly, when I ran it without debugging, it segfaulted immediately. When I ran it in the debugger, it paused after the first "New Thread" output (`[New Thread 0x7ffff5b22640 (LWP 14670)]`) for about a minute before rapidly spitting out the rest and then segfaulting.

The system is a 64-bit Gentoo Linux:
```
$ uname -a
Linux Hugin 5.6.7-gentoo #13 Mon Jan 25 06:54:51 EST 2021 x86_64 Intel(R) Core(TM) i5-3360M CPU @ 2.80GHz GenuineIntel GNU/Linux
```

I might be able to run this on a Windows machine instead, but figured you might want to know about this.

Thank you for at least releasing a Linux build, even if it didn't (or hasn't yet) worked for me. :)

**Comment by ferru97** [comment]
Hi @chadjoan, thanks for your interest!
I tested it on Manjaro 21 and it seems to work. As soon as I can I take a look at this problem
